[package]
name = "orias"
authors = ["BradenEverson", "MSOEDroneClub"]
description = "Computer Vision library with embedded systems support"
version = "0.1.1"
edition = "2021"
license = "MIT"

[lib]
no_std = true

[dependencies]
